const scenariosDefault = [
  {id:301, sender:'BDO Alert', body:'Security notice: We blocked a login. Verify with OTP: [link]', type:'otp'},
  {id:302, sender:'BDO Notice', body:'BDO warns: Do not click unknown SMS links. See security tips: [link]', type:'cred'},
  {id:303, sender:'BDO', body:'Alert: Confirm recent transaction ₱5,000. Visit: [link]', type:'cred'},
  {id:304, sender:'BDO-Sec', body:'Urgent: Reset your e-banking password to avoid lockout: [link]', type:'cred'},
  {id:311, sender:'LBC', body:'Delivery attempt failed. Confirm address to re-schedule: [link]', type:'info'},
  {id:312, sender:'J&T', body:'Parcel on hold. Provide ID & confirm here: [link]', type:'cred'},
  {id:313, sender:'2GO', body:'Pickup code 882-91. Enter code to claim: [link]', type:'info'},
  {id:314, sender:'LBC', body:'Notice: Update delivery preferences here: [link]', type:'cred'},
  {id:321, sender:'Globe Care', body:'Account suspension in 24h. Restore at: [link]', type:'cred'},
  {id:322, sender:'Smart Services', body:'SIM verification required — enter one-time code: [link]', type:'otp'},
  {id:323, sender:'Teleco', body:'Unusual usage detected. Verify to avoid charges: [link]', type:'cred'},
  {id:331, sender:'Payroll Dept', body:'Salary release pending — confirm bank details: [link]', type:'cred'},
  {id:332, sender:'BIR Refund', body:'You have a tax refund. Claim here: [link]', type:'info'},
  {id:333, sender:'SSS', body:'Contribution mismatch detected. Update records: [link]', type:'cred'},
  {id:341, sender:'DepEd Admin', body:'Update teacher records: [link]', type:'cred'},
  {id:342, sender:'School IT', body:'Shared staff roster: open to view: [link]', type:'cred'},
  {id:343, sender:'Colleague Maria', body:'Can you check this attendance sheet? [link]', type:'cred'},
  {id:344, sender:'Principal Office', body:'Important memo: read here (LMS): [link]', type:'legit'},
  {id:351, sender:'Google Drive', body:'Document shared with you: "Final Grades". Open: [link]', type:'cred'},
  {id:352, sender:'Dropbox', body:'New secure file for you. View now: [link]', type:'cred'},
  {id:353, sender:'OneDrive', body:'Shared: "Learner List 2025". Click to view: [link]', type:'cred'},
  {id:361, sender:'Facebook', body:'Account flagged. Verify identity here: [link]', type:'cred'},
  {id:362, sender:'Meta Support', body:'New login from unknown device. Enter OTP: [link]', type:'otp'},
  {id:363, sender:'Instagram', body:'Verify to restore access: [link]', type:'cred'},
  {id:371, sender:'SmartPromo', body:'Free load ₱100 for first 1,000 claimants: [link]', type:'info'},
  {id:372, sender:'Shopee PH', body:'Order #12345 unpaid. Pay to avoid cancellation: [link]', type:'cred'},
  {id:373, sender:'Grab', body:'Ride refund processed — claim here: [link]', type:'info'},
  {id:381, sender:'BDO', body:'Verify transaction at bdo-secure[dot]ph: [link]', type:'cred'},
  {id:382, sender:'BDO', body:'BDO: Important security update — visit: bit.ly/BDO-update [link]', type:'cred'},
  {id:383, sender:'BDO-Support', body:'We will never ask for OTP. Report phishing here: [link]', type:'info'},
  {id:391, sender:'City Health', body:'Free vaccine registration for teachers. Sign up: [link]', type:'info'},
  {id:392, sender:'Clinic', body:'Your appointment needs confirmation. Click to confirm: [link]', type:'info'},
  {id:401, sender:'BankPH', body:'We updated terms. Log in to accept: [link]', type:'cred'},
  {id:402, sender:'Bank Alert', body:'Unusual withdrawal flagged. Confirm or lock account: [link]', type:'cred'},
  {id:403, sender:'eBank', body:'Temporary hold on account until verification: [link]', type:'cred'},
  {id:411, sender:'IT Support', body:'Mandatory password reset for staff. Reset now: [link]', type:'cred'},
  {id:412, sender:'Helpdesk', body:'We detected malware on your workstation. Run this scan: [link]', type:'info'},
  {id:421, sender:'HR Dept', body:'Update your emergency contact for benefits: [link]', type:'cred'},
  {id:422, sender:'Benefits', body:'Claim wellness stipend: fill form: [link]', type:'cred'},
  {id:431, sender:'Shared Doc', body:'You were added to: "Class Photos 2025". View: [link]', type:'cred'},
  {id:432, sender:'Google Calendar', body:'Invitation: "Parent-Teacher Meet". Accept: [link]', type:'info'},
  {id:441, sender:'Alert', body:'We found suspicious files in your Drive. Review here: [link]', type:'cred'},
  {id:442, sender:'Security', body:'Your password expires today. Renew here: [link]', type:'cred'},
  {id:451, sender:'Payment', body:'Failed automatic payment. Update card: [link]', type:'cred'},
  {id:452, sender:'Wallet', body:'Verify recent charge to avoid reversal: [link]', type:'cred'},
  {id:461, sender:'Survey', body:'Participate to win ₱2,000 gift card: [link]', type:'info'},
  {id:462, sender:'Contest', body:'You are selected. Claim prize here: [link]', type:'cred'},
  {id:471, sender:'Colleague', body:'Quick favor: sign this form for me: [link]', type:'cred'},
  {id:472, sender:'Staff', body:'Meeting notes uploaded: open to view: [link]', type:'info'},
  {id:481, sender:'PhishTest', body:'This message is a phishing test. Click to learn: [link]', type:'info'},
  {id:482, sender:'Security Lab', body:'If you clicked previous link, record here: [link]', type:'info'},
  {id:491, sender:'Bank Notice', body:'Security bulletin: we will never ask for OTP via SMS. See more: [link]', type:'info'},
  {id:492, sender:'Alert', body:'Important: Download secure app update: [link]', type:'cred'},
  {id:501, sender:'Delivery', body:'Your barangay delivery needs verification. Confirm ID here: [link]', type:'cred'},
  {id:502, sender:'Marketplace', body:'Buyer paid. Release item: [link]', type:'cred'},
  {id:511, sender:'EduPortal', body:'Grades uploaded. Teacher action required: [link]', type:'cred'},
  {id:512, sender:'LMS', body:'New submission requires moderation. Open: [link]', type:'cred'},
  {id:521, sender:'ISP', body:'Service upgrade required. Schedule technician: [link]', type:'info'},
  {id:522, sender:'Utilities', body:'Billing dispute notice. Respond here: [link]', type:'cred'},
  {id:531, sender:'Bank Reminder', body:'We sent you a security warning. Verify here: [link]', type:'cred'},
  {id:532, sender:'Notice', body:'You received a new message from "Admin". Open to read: [link]', type:'cred'},
  {id:541, sender:'Promo', body:'Flash sale — exclusive link for teachers: [link]', type:'info'},
  {id:542, sender:'Vendor', body:'Confirm payment to release order: [link]', type:'cred'},
  {id:551, sender:'Verifier', body:'Confirm your identity to access government services: [link]', type:'cred'},
  {id:552, sender:'GovPortal', body:'Your application requires signature. Sign here: [link]', type:'cred'},
  {id:561, sender:'ShortURL', body:'Check this quick link: tinyurl.com/teach-update [link]', type:'cred'},
  {id:562, sender:'ShortURL', body:'Notice from BDO: short link bit.ly/bdo-verify [link]', type:'cred'},
  {id:571, sender:'TypoBDO', body:'BDO Security: Verify at bdo-secure[dot]ph to avoid lock: [link]', type:'cred'},
  {id:572, sender:'TypoGlobe', body:'Gl0be Support: Confirm sim at gl0be-verify[dot]ph: [link]', type:'cred'},
  {id:581, sender:'Control', body:'Reminder: Submit lesson plans via official LMS only. No action required.', type:'legit'},
  {id:582, sender:'Principal', body:'Monthly memo: Meeting tomorrow at 3PM. See agenda: [link]', type:'legit'},
  {id:701, sender: 'Globe Rewards',body: 'Extend a helping hand with Globe Rewards. Tap REDEEM REWARDS and JOIN NOW to use your welcome Rewards points as donation to Rise Against Hunger to help bring aid and warm meals to affected communities. Use GlobeOne to register to your favorite promos to get more points. Globe will NEVER send texts with links. REF #LS',type: 'info'},
  {id:702,sender: 'BDO Customer Care',body: 'Important: For your protection we temporarily placed a hold on your eBanking after multiple failed login attempts. To restore full access and review recent transactions, please follow the secure verification flow here: [link]. If you do not verify within 48 hours your account may be temporarily limited. Contact BDO hotline if unsure.',type: 'cred'},
  {id:703,sender: 'Payroll Services',body: 'Notice to all teaching staff: Due to an update in payroll batching some salary disbursements require confirmation of receiving bank details. Please confirm your account number and routing information immediately to avoid payment delays for this pay cycle. Confirm now at: [link]. This is required to process your June payroll on schedule.',type: 'cred'},
  {id:704,sender: 'LBC Customer Care',body: 'We attempted delivery but there was no one to receive your package. To avoid return-to-sender and additional fees please confirm the exact delivery address and preferred pickup window using the secure link: [link]. If you recently updated your address online, ignore this message. Reference: LBC#49321.',type: 'info'},
  {id:705,sender: 'DepEd Admin',body: 'URGENT: Please update your personal profile and teaching certifications in the central registry before the end of month to remain compliant with the new DepEd audit. Click the secure staff portal to upload scanned certificates and signed consent form: [link]. Failure to update may affect next term’s teacher allocation.',type: 'cred'},
  {id:706,sender: 'SSS Notification',body: 'Alert: A discrepancy was detected in your recent SSS contribution record which may delay benefits processing. Review the discrepancy details and submit supporting documents here: [link]. This message contains time-sensitive instructions — submit within 7 days to prevent claim delays.',type: 'cred'},
  {id:707,sender: 'Health City Program',body: 'Free medical outreach registration for teachers: Limited slots available this weekend. Register at the community health portal to reserve your slot and receive confirmation code via SMS: [link]. Please bring ID and registration confirmation to the clinic. This outreach is prioritized for educators and staff.',type: 'info'},
  {id:708,sender: 'Google Drive',body: 'A colleague shared a document: "CONFIDENTIAL Staff Roster — Salary Adjustments". To view the file, sign in and accept the sharing permission here: [link]. This file was set to expire for non-views — open now to retain access. Contact IT if you believe this was sent in error.',type: 'cred'},
  {id:709,sender: 'Telco Alerts',body: 'Service update: We detected unusual SIM activity on your number which could affect mobile banking verifications. To secure your line and confirm authorized devices, complete the quick SIM verification at: [link]. Note: this verification is required to restore mobile banking access for linked apps.',type: 'otp'},
  {id:710,sender: 'Promo Center',body: 'Congratulations! You were shortlisted for a teacher-exclusive voucher bundle worth ₱2,500. Tap CLAIM to verify eligibility and schedule delivery. Limited redemption window — unclaimed vouchers will be returned to pool within 24 hours. Verify here: [link]. Terms apply.',type: 'info'},
  {id:801,sender: 'GCash Support',body: 'Important: We have temporarily restricted certain transactions on your GCash account for security reasons. To restore full access and confirm recent high-value transfers, please verify your identity here: [link]. Verification requires entering the one-time code sent to your number and confirming the last four digits of your linked bank account. Failure to verify within 48 hours may result in a temporary hold.',type: 'cred'},
  {id:802,sender: 'GCash Alerts',body: 'Notice: Unrecognized device attempted to access your account. Confirm device & recent activity to prevent unauthorized transfers. Use this secure verification: [link]. We will never ask for your MPIN via SMS. If you did not attempt access, please report immediately to GCash Help.',type: 'otp'},
  {id:803,sender: 'Pag-IBIG Fund',body: 'Pag-IBIG: A new online member benefit requires verification of your membership number to process housing loan eligibility. Please confirm your name, membership ID, and birthdate via this secure portal: [link]. This is part of the annual membership data-cleanup initiative. Incorrect or missing data may delay your application.',type: 'cred'},
  {id:804,sender: 'PagIBIG Notice',body: 'Pag-IBIG: Your contribution record shows a mismatch for the last quarter. To view details and upload supporting documents (PDF or image), access the member portal: [link]. Uploads must be completed within 14 days to avoid penalties. Contact Pag-IBIG hotline for verification.',type: 'cred'},
  {id:805,sender: 'SSS Alert',body: 'SSS Notification: We detected a potential issue with your SSS number linking that may affect loan applications and benefit claims. Review the flagged entries and submit corrections through the SSS online account portal: [link]. You may be asked to scan and upload supporting IDs — ensure files are clear and legible.',type: 'cred'},
  {id:806,sender: 'SSS Helpdesk',body: 'SSS: A new contribution notice was generated for your account. If this was not initiated by you, immediately confirm recent transactions and secure your account at: [link]. For faster assistance, have your SSS ID and registered mobile number ready.',type: 'info'},
  {id:807,sender: 'TNT Alerts',body: 'TNT: Due to a system upgrade, some customers need to re-authorize their prepaid accounts to keep promotions active. Tap to re-authorize and claim your remaining promo load: [link]. Promotion restores are time-limited and require confirmation of your mobile number — do not share OTPs with anyone.',type: 'info'},
  {id:808,sender: 'TNT Service',body: 'TNT Security: We detected SIM swap attempt risk. Secure your SIM now by confirming your last recharge transaction and entering the verification code sent via SMS: [link]. If you did not request this, report to TNT immediately. This step prevents account takeover for linked services.',type: 'otp'},
  {id:809,sender: 'TikTok Support',body: 'TikTok Safety: Your creator account shows unusual sign-in attempts. To secure your channel and avoid removal, verify your identity and recent uploads at: [link]. Verification helps prevent unauthorized monetization changes. Use only the official app or the link shown here (demo).',type: 'cred'},
  {id:810,sender: 'TikTok Team',body: 'TikTok: Your account has been shortlisted for creator rewards. Claim your bonus by confirming your payout details and providing a short verification clip via the creator portal: [link]. Failure to confirm within 72 hours will forfeit the reward.',type: 'info'},
  {id:811,sender: 'Maya Bank',body: 'Maya: Immediate action required. We identified an irregular transfer attempt. To freeze the transaction and verify beneficiary details, follow the secure verification link: [link]. You will be asked for a one-time confirmation code for this session. Keep your account secure by using the official app only.',type: 'otp'},
  {id:812,sender: 'Maya Alerts',body: 'Maya Bank: Routine security update — confirm your email and phone numbers to continue receiving e-statements and bank alerts. Visit the secure update portal to confirm contact details and enable two-factor authentication: [link]. This will improve account notification reliability.',type: 'cred'},
  {id:813,sender: 'GCash Promo',body: 'GCash: Share your spare change and earn rewards. Redeem points for token donations or cashback. Tap REDEEM to see eligible promos and verify your GCash account status to claim a match bonus: [link]. Limited offers for verified users only.',type: 'info'},
  {id:814,sender: 'Pag-IBIG HR',body: 'HR Notice via Pag-IBIG portal: We are processing housing benefit enrollments for eligible teachers. Confirm your current address, marital status, and beneficiary details by uploading the signed form here: [link]. Submission deadline is close; incomplete records may be excluded.',type: 'cred'},
  {id:815,sender: 'SSS Benefits',body: 'SSS: Your disability/loan application has pending items. Review the checklist and upload required documents at the secure link: [link]. Documents must be valid government-issued IDs and certified copies where applicable. This helps expedite claim processing.',type: 'info'},
  {id:816,sender: 'TikTok Notice',body: 'Security alert: a third-party app requested access to your TikTok data. Revoke access or reauthorize safely via the security center: [link]. We recommend revoking any unknown apps and changing your password if you did not grant access.',type: 'cred'},
  {id:817,sender: 'Maya Verification',body: 'Maya: New payment method added to your account. Confirm this change to prevent unauthorized charges by reviewing linked cards and transactions at: [link]. If you do not recognize this activity, lock your payment method immediately.',type: 'cred'},
  {id:818,sender: 'TNT Promo',body: 'TNT Reward: Exclusive teacher bundle available. Redeem now by confirming your mobile number and promo code on the secure portal: [link]. Promo allocations are limited and require confirmation of eligibility through OTP verification.',type: 'info'},
  {id:819,sender: 'GCash Security',body: 'Security advisory: We observed attempts to trick users with fake “GCash support” messages telling users to reset their MPIN. GCash will never ask for your MPIN or full password through links. For your safety, confirm suspicious messages here: [link]. (This is a simulation test.)',type: 'info'},
  {id:820,sender: 'Pag-IBIG Update',body: 'Automated: Important update to Pag-IBIG member portal terms. Review and accept changes to continue accessing your account features, including housing loan pre-qualification tools. Access the member agreement and indicate acceptance here: [link].',type: 'cred'},
  {id:901,sender: 'Gmail Security',body: 'Security alert: We detected a sign-in attempt from a new device on your Gmail account. If this was you, verify the device and confirm activity using the secure link here: [link]. If you do not recognize the device, follow the steps to secure your account and change your recovery options immediately.',type: 'cred'},
  {id:902,sender: 'Google Account',body: 'Google: Important privacy update. To continue using certain account features and keep your data synced, review and accept the updated settings here: [link]. Review now to avoid interruption to Drive, Photos, and Classroom integrations. This is part of a phased rollout.',type: 'cred'},
  {id:903,sender: 'Gmail Helpdesk',body: 'Notice: Your mailbox is nearing storage capacity. Free up space or purchase additional storage to avoid delivery failures. Click here to manage storage and transfer files: [link]. We recommend reviewing large attachments and shared drives.',type: 'info'},
  {id:904,sender: 'Google Play',body: 'Payment problem: A recent charge could not be processed. Verify your Google payment method to avoid suspension of paid apps and subscriptions: [link]. This may affect classroom apps tied to your account.',type: 'cred'},
  {id:905,sender: 'Microsoft Account',body: 'Microsoft Alert: Unusual activity detected on your Microsoft account. To secure access to Teams, Outlook, and OneDrive, verify your identity and recent sign-ins here: [link]. If you use Single Sign-On at work, inform your IT before making changes.',type: 'otp'},
  {id:906,sender: 'Office 365 Admin',body: 'Admin notice: Your tenant requires admin consent for a new integration. Click to review requested permissions and approve or deny the app on behalf of your organization: [link]. Do not approve unfamiliar apps — consult your IT admin.',type: 'cred'},
  {id:907,sender: 'Microsoft Support',body: 'Account recovery required: We found a change in your account recovery settings. Confirm your alternate email and phone number to avoid lockout: [link]. Recovery confirmation will help you regain access if credentials are compromised.',type: 'cred'},
  {id:908,sender: 'DEPED LIS',body: 'DEPED LIS: Immediate action required. Please update learner and teacher records for year-end audit. Upload scanned certificates and confirm identifiers via the LIS portal: [link]. Missing or mismatched entries may delay batch reporting.',type: 'cred'},
  {id:909,sender: 'DEPED Support',body: 'LIS maintenance notice: Some accounts require reactivation to continue accessing learner data. Reactivate your staff account by confirming your employee number and recent activity here: [link]. Use official channels if unsure.',type: 'info'},
  {id:910,sender: 'Google Classroom',body: 'Action required: A parent reported missing grades. To review the shared gradebook and resolve discrepancies, sign in to the secure teacher portal: [link]. Changes will be logged — keep supporting documents ready.',type: 'cred'},
  {id:911,sender: 'Microsoft Teams',body: 'Security notice: We blocked a sign-in to your Teams account from an unfamiliar location. Verify the recent sign-in and reset session tokens to continue meetings without interruption: [link]. If you use Teams for classes, confirm now.',type: 'otp'},
  {id:912,sender: 'Google Admin',body: 'Policy update: New admin security policies are being rolled out. Review the required two-step verification enforcement and exempted accounts here: [link]. Confirm your account compliance to avoid access changes to Google Workspace services.',type: 'info'},
  {id:995, sender: 'School Notice', body: 'Reminder: Tomorrow is a non-teaching day for district-wide training. No classes. Submit lesson plans and grade sheets by 5:00 PM to the office drive if not already uploaded.', type: 'info' },
  {id:996, sender: 'Principal Office', body: 'All staff: Monthly staff meeting at 3:00 PM in the multipurpose hall. Agenda: learner welfare, inventory, and upcoming parent-teacher conference. Attendance required.', type: 'legit' },
  {id:997, sender: 'IT Support', body: 'Planned network maintenance tonight 11:00 PM–1:00 AM. School systems (LMS, email, portal) will be intermittently unavailable. Save your work and log out before maintenance.', type: 'info' },
  {id:998, sender: 'Payroll Dept', body: 'Payroll processed. Salary disbursement for this month will reflect on your account by Friday. Contact HR for discrepancies; do not reply to this message with bank details.', type: 'legit' },
  {id:999, sender: 'Clinic', body: 'Free vaccination drive for staff this Saturday at the health center. Bring valid ID and employee number. Slots limited — walk-ins welcome from 8:00–11:00 AM.', type: 'info' },
  {id:1000, sender: 'Library', body: 'New learning resources available: downloadable teacher guides and supplemental materials for Grade 4–6. Visit the library portal to borrow or download.', type: 'info' },
  {id:1001, sender: 'Safety Office', body: 'Fire drill scheduled Monday 9:30 AM. Assemble at designated evacuation points. Do not use elevators. Report absent staff to the office immediately after drill.', type: 'legit' },
  {id:1002, sender: 'Enrollment', body: 'Reminder: Open enrollment for summer classes starts next week. Submit student lists and required documents to the registrar by the deadline to avoid delays.', type: 'info' },
  {id:1003, sender: 'HR', body: 'Policy update: Remote work guidelines and leave filing procedure have been updated. View the updated policy on the staff portal and acknowledge receipt within 7 days.', type: 'legit' },
  {id:1004, sender: 'Survey', body: 'Quick staff survey: Please complete the 2-minute form about classroom resource needs. Your input will be used for next term’s budget planning. Link posted on staff channel.', type: 'info' },
  {id:1005, sender:'Guidance Office', body:'Reminder: Parent-teacher conference sign-up sheet is open. Please register your preferred slot by Tuesday to help with room assignments.', type:'info' },
  {id:1006, sender:'Transport', body:'School shuttle schedule update: Route A pickup moved to 7:10 AM starting Monday. Check the staff transport board for details.', type:'info' },
  {id:1007, sender:'Canteen', body:'Menu update: New healthy meal options available this week. Special discount for staff between 11:00–12:00. Cashless payments accepted.', type:'info' },
  {id:1008, sender:'Facilities', body:'Lighting maintenance in Block B will happen tomorrow from 8:00–10:00 AM. Expect temporary power interruptions in nearby rooms.', type:'info' },
  {id:1009, sender:'Records', body:'Student records submission deadline extended by 3 days. Submit scanned copies to the registrar platform to avoid processing delays.', type:'legit' },
  {id:1010, sender:'Training Unit', body:'Sign-up: Free online workshop on differentiated instruction this Thursday 6:00 PM. Limited seats; register via the staff portal.', type:'info' },
  {id:1011, sender:'Health Desk', body:'Reminder: Annual staff medical check-up starts next week. Bring your medical forms and valid ID. Walk-in slots available on Wednesday.', type:'info' },
  {id:1012, sender:'IT Notifications', body:'Two-factor authentication will be enforced next month. Enroll your mobile number and backup email on the staff security page.', type:'legit' },
  {id:1013, sender:'Registrar', body:'Confirmation: Graduation list draft has been published. Review student names and submit corrections within 5 working days.', type:'legit' },
  {id:1014, sender:'Community Liaison', body:'Volunteers needed for the school outreach program this Saturday. Report to the canteen at 7:30 AM. Transportation and lunch provided.', type:'info' },
  {id:1035, sender:'SSS', body:'Reminder: Your SSS contribution for this month is pending. Log in to the member portal to update.', type:'legit' },
  {id:1036, sender:'PagIBIG Fund', body:'Notice: PagIBIG online payment is available until 11:59 PM today to avoid penalties.', type:'legit' },
  {id:1037, sender:'GCash', body:'Action Needed: Your account verification is incomplete. Verify now to continue sending funds.', type:'legit' },
  {id:1038, sender:'TNT', body:'Promo: Load up your TNT number today and get 20% bonus on your first top-up.', type:'info' },
  {id:1039, sender:'MayaBank', body:'Alert: Unusual login detected on your account. If not you, secure your account immediately.', type:'legit' },
  {id:1040, sender:'TikTok', body:'Notice: Your video failed to upload due to file format. Re-upload in MP4 format.', type:'info' },
  {id:1041, sender:'Gmail', body:'Security Alert: Suspicious sign-in attempt detected. Review your recent activity now.', type:'legit' },
  {id:1042, sender:'Google', body:'Action Required: Your Google Drive storage is almost full. Upgrade to continue uploading files.', type:'info' },
  {id:1043, sender:'Microsoft Account', body:'Alert: Unusual activity detected. Reset your password immediately to protect your account.', type:'legit' },
  {id:1044, sender:'DepEd LIS', body:'Reminder: Update your learner information system profile before the end of the month.', type:'legit' },
  {id:1055, sender:'Library', body:'Reminder: Return borrowed books by Friday to avoid overdue fines.', type:'info' },
  {id:1056, sender:'HR', body:'Update: New policy on work-from-home arrangements effective next month. Check the HR portal for details.', type:'legit' },
  {id:1057, sender:'IT Support', body:'Scheduled maintenance: Intranet will be down on Saturday 10:00 PM–2:00 AM. Plan accordingly.', type:'info' },
  {id:1058, sender:'Canteen', body:'Notice: Daily meal specials are now posted online. Check before ordering.', type:'info' },
  {id:1059, sender:'Finance', body:'Reminder: Submit expense reports by the 25th of this month to ensure processing.', type:'legit' },
  {id:1060, sender:'Training Unit', body:'Upcoming webinar: Effective teaching strategies for online classrooms this Wednesday 5:00 PM.', type:'info' },
  {id:1061, sender:'Health Desk', body:'Announcement: Free blood pressure check-up available this Thursday in the staff lounge.', type:'info' },
  {id:1062, sender:'Registrar', body:'Deadline extended: Enrollment forms must be submitted by the end of the week.', type:'legit' },
  {id:1063, sender:'Transport', body:'Notice: Shuttle service will operate on an adjusted schedule during the holidays.', type:'info' },
  {id:1064, sender:'IT Notifications', body:'Reminder: Update your staff portal password every 90 days to maintain access.', type:'legit' },
  {id:1065, sender:'Community Liaison', body:'Event: School fundraising bazaar this Saturday from 9:00 AM–3:00 PM. Volunteers welcome.', type:'info' },
  {id:1066, sender:'HR', body:'Reminder: Staff appraisal forms must be completed by Friday. Access via HR portal.', type:'legit' },
  {id:1067, sender:'Library', body:'Update: Extended library hours from 7:00 AM–7:00 PM starting next week.', type:'info' },
  {id:1068, sender:'Finance', body:'Notice: Tax declaration submission deadline is approaching. Submit online to avoid penalties.', type:'legit' },
  {id:1069, sender:'Canteen', body:'Special: Healthy snack options available for staff at discounted prices from 2:00–4:00 PM.', type:'info' },
  {id:1070, sender:'Training Unit', body:'Reminder: Register for the mandatory first aid training scheduled next Tuesday.', type:'info' },
  {id:1071, sender:'Health Desk', body:'Notice: Staff mental wellness check-ins available this week. Schedule via the portal.', type:'info' },
  {id:1072, sender:'Registrar', body:'Update: Graduation list has been finalized. Confirm student names and report discrepancies within 3 days.', type:'legit' },
  {id:1073, sender:'IT Support', body:'Reminder: Two-factor authentication will be enforced starting next month. Update your account.', type:'legit' },
  {id:1074, sender:'Facilities', body:'Maintenance: Air conditioning in Block A will be serviced tomorrow from 9:00 AM–12:00 NN.', type:'info' }

]